language: scala
jdk: oraclejdk8
scala: dummy # using crossScalaVersions over TRAVIS_SCALA_VERSION
before_script: cd sbt-sample
script: sbt +update

cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt

before_cache:
  - find $HOME/.ivy2/cache -name "ivydata-*.properties" -print -delete
  - find $HOME/.sbt        -name "*.lock"               -print -delete
